all:
	gcc -o hello1 hello1.c -lcurses
	gcc -o hello2 hello2.c -lcurses
	gcc -o hello3 hello3.c -lcurses
	gcc -o hello4 hello4.c -lcurses
	gcc -o hello5 hello5.c -lcurses
	gcc -o sigdemo3 sigdemo3.c
	gcc -o sleep1 sleep1.c
	gcc -o ticker_demo ticker_demo.c 
	gcc -o bounce1d bounce1d.c set_ticker.c -lcurses
clean:
	rm -f hello1 hello2 hello3 hello4 hello5 sleep1 sigdemo3 ticker_demo bounce1d